//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Block_UI_for_Gear.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: anand
//              Version: Designcenter 2512
//              Date: 06-20-2026  (Format: mm-dd-yyyy)
//              Time: 11:19 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
namespace GearGenerationPlugin
{
    public class Block_UI_for_Gear
    {
        //class members
        private static Session theSession = null;
        private static UI theUI = null;
        private string theDlxFileName;
        private NXOpen.BlockStyler.BlockDialog theDialog;
        private NXOpen.BlockStyler.Group group0;
        private NXOpen.BlockStyler.IntegerBlock blockTeeth;// Block type: Integer
        private NXOpen.BlockStyler.LinearDimension blockModule;// Block type: Linear Dim
        private NXOpen.BlockStyler.LinearDimension blockFaceWidth;// Block type: Linear Dim
        private NXOpen.BlockStyler.AngularDimension blockPressureAngle;// Block type: Angular Dim
        private NXOpen.BlockStyler.RadiusDimension blockShaftDia;// Block type: Radius Dim
                                                                 //------------------------------------------------------------------------------
                                                                 //Bit Option for Property: SnapPointTypesOnByDefault
                                                                 //------------------------------------------------------------------------------
        public static readonly int SnapPointTypesOnByDefault_UserDefined = (1 << 0);
        public static readonly int SnapPointTypesOnByDefault_Inferred = (1 << 1);
        public static readonly int SnapPointTypesOnByDefault_ScreenPosition = (1 << 2);
        public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
        public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
        public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
        public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
        public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
        public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
        public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
        public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
        public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
        public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);
        public static readonly int SnapPointTypesOnByDefault_TwocurveIntersection = (1 << 13);
        public static readonly int SnapPointTypesOnByDefault_TangentPoint = (1 << 14);
        public static readonly int SnapPointTypesOnByDefault_Poles = (1 << 15);
        public static readonly int SnapPointTypesOnByDefault_BoundedGridPoint = (1 << 16);
        public static readonly int SnapPointTypesOnByDefault_FacetVertexPoint = (1 << 17);
        public static readonly int SnapPointTypesOnByDefault_DefiningPoint = (1 << 18);

        //------------------------------------------------------------------------------
        //Constructor for NX Styler class
        //------------------------------------------------------------------------------
        public Block_UI_for_Gear()
        {
            try
            {
                theSession = Session.GetSession();
                theUI = UI.GetUI();
                // Get the folder where this currently running .dll is located
                string dllFolder = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);

                // Combine it with the .dlx name
                theDlxFileName = System.IO.Path.Combine(dllFolder, "Gear_Block_UI.dlx");
                theDialog = theUI.CreateDialog(theDlxFileName);
                theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
                theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
                theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
                theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
                theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                throw ex;
            }
        }
        //------------------------------- DIALOG LAUNCHING ---------------------------------
        //
        //    Before invoking this application one needs to open any part/empty part in NX
        //    because of the behavior of the blocks.
        //
        //    Make sure the dlx file is in one of the following locations:
        //        1.) From where NX session is launched
        //        2.) $UGII_USER_DIR/application
        //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
        //            recommended. This variable is set to a full directory path to a file 
        //            containing a list of root directories for all custom applications.
        //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
        //
        //    You can create the dialog using one of the following way:
        //
        //    1. Journal Replay
        //
        //        1) Replay this file through Tool->Journal->Play Menu.
        //
        //    2. USER EXIT
        //
        //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
        //        2) Invoke the Shared Library through File->Execute->NX Open menu.
        //
        //------------------------------------------------------------------------------
        

        //------------------------------------------------------------------------------
        // Following method cleanup any housekeeping chores that may be needed.
        // This method is automatically called by NX.
        //------------------------------------------------------------------------------
        public static void UnloadLibrary(string arg)
        {
            try
            {
                //---- Enter your code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //This method launches the dialog to screen
        //------------------------------------------------------------------------------
        public NXOpen.BlockStyler.BlockDialog.DialogResponse Launch()
        {
            NXOpen.BlockStyler.BlockDialog.DialogResponse dialogResponse = NXOpen.BlockStyler.BlockDialog.DialogResponse.Invalid;
            try
            {
                dialogResponse = theDialog.Launch();
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return dialogResponse;
        }

        //------------------------------------------------------------------------------
        //Method Name: Dispose
        //------------------------------------------------------------------------------
        public void Dispose()
        {
            if (theDialog != null)
            {
                theDialog.Dispose();
                theDialog = null;
            }
        }

        //------------------------------------------------------------------------------
        //---------------------Block UI Styler Callback Functions--------------------------
        //------------------------------------------------------------------------------

        //------------------------------------------------------------------------------
        //Callback Name: initialize_cb
        //------------------------------------------------------------------------------
        public void initialize_cb()
        {
            try
            {
                group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
                blockTeeth = (NXOpen.BlockStyler.IntegerBlock)theDialog.TopBlock.FindBlock("blockTeeth");
                blockModule = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("blockModule");
                blockFaceWidth = (NXOpen.BlockStyler.LinearDimension)theDialog.TopBlock.FindBlock("blockFaceWidth");
                blockPressureAngle = (NXOpen.BlockStyler.AngularDimension)theDialog.TopBlock.FindBlock("blockPressureAngle");
                blockShaftDia = (NXOpen.BlockStyler.RadiusDimension)theDialog.TopBlock.FindBlock("blockShaftDia");
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: dialogShown_cb
        //This callback is executed just before the dialog launch. Thus any value set 
        //here will take precedence and dialog will be launched showing that value. 
        //------------------------------------------------------------------------------
        public void dialogShown_cb()
        {
            try
            {
                //---- Enter your callback code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: apply_cb
        //------------------------------------------------------------------------------
        public int apply_cb()
        {
            int errorCode = 0;
            try
            {
                // 1. Safety Check: Make sure a part is open!
                if (!NXSessionManager.EnsureWorkPartExists()) return 1;

                // 2. Create the "Save State" (Undo Mark)
                Session.UndoMarkId markId = NXSessionManager.SetUndoMark("Generate Spur Gear");

                try
                {
                    // 3. Extract LIVE inputs from your custom UI blocks
                    int teeth = blockTeeth.Value;
                    double moduleVal = blockModule.Value;
                    double facewidth = blockFaceWidth.Value;
                    double pressureAngleDeg = blockPressureAngle.Value;
                    double shaftHoleDia = blockShaftDia.Value;

                    // Pack them into your Data Object (The Box)
                    GearParameters myGearData = new GearParameters(teeth, moduleVal, facewidth, pressureAngleDeg, shaftHoleDia);

                    // Validate the inputs (The Bouncer)
                    GearValidator.Validate(myGearData);

                    // Build the gear! (The Engine)
                    SpurGearBuilder.BuildGear(NXSessionManager.WorkPart, myGearData);

                    return 0; // Success! NX will automatically keep the geometry.
                }
                catch (Exception ex)
                {
                    // 4. THE SAFETY NET: If ANYTHING above fails, roll back the NX file instantly.
                    NXSessionManager.UndoToMark(markId, "Generate Spur Gear");

                    // Tell the user exactly what went wrong without breaking the file
                    NXSessionManager.ShowMessage("Gear Generation Failed", ex.Message, NXMessageBox.DialogType.Error);
                    return 1;
                }
            }
            catch (Exception ex)
            {
                // Absolute fallback for major system errors
                errorCode = 1;
                UI.GetUI().NXMessageBox.Show("Block Styler Error", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Callback Name: update_cb
        //------------------------------------------------------------------------------
        public int update_cb(NXOpen.BlockStyler.UIBlock block)
        {
            try
            {
                if (block == blockTeeth)
                {
                    //---------Enter your code here-----------
                }
                else if (block == blockModule)
                {
                    //---------Enter your code here-----------
                }
                else if (block == blockFaceWidth)
                {
                    //---------Enter your code here-----------
                }
                else if (block == blockPressureAngle)
                {
                    //---------Enter your code here-----------
                }
                else if (block == blockShaftDia)
                {
                    //---------Enter your code here-----------
                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Callback Name: ok_cb
        //------------------------------------------------------------------------------
        public int ok_cb()
        {
            int errorCode = 0;
            try
            {
                errorCode = apply_cb();
                //---- Enter your callback code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Function Name: GetBlockProperties
        //Returns the propertylist of the specified BlockID
        //------------------------------------------------------------------------------
        public PropertyList GetBlockProperties(string blockID)
        {
            PropertyList plist = null;
            try
            {
                plist = theDialog.GetBlockProperties(blockID);
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return plist;
        }

    }
}